### PR TITLE
Revert "Revert "Us20 t77 project info""

### PR DESCRIPTION
**Pull request by zawata**
undo the revert to re-open the PR @HalcyonAura

### CODE REVIEW

**Comment by zawata** [comment]
hey david. try not to merge this one

**Comment by HalcyonAura** [comment]
How to test
To test add this line (and import project_info) to any one of the front end .js files in the project and view the output in the console window

```
{console.log(project_info('halcyonaura-quiz-creator').then((val)=> 
              {console.log('fe', val)}
              ))}
```
You should get the following values:
`{id: 309976, name: "Quiz Creator", slug: "halcyonaura-quiz-creator", created_date: "2019-02-15T01:07:23.636Z"}`

**Comment by dlahtine** [comment]
okie dokie, looks good to me boss.

**Comment by zawata** [comment]
works perfectly. approved :+1:

**Pull request merged**
