### PR TITLE
Merging final work into master

### PR DESCRIPTION
**Pull request by trevorforrey**

### CODE REVIEW

**Comment by trevorforrey** [comment]
I don't think I'll have time to fix the team page, we could add this as an issue but still merge what we have into master?

**Comment by vmadaraj** [comment]
@trevorforrey I have approved the changes. Lets just make sure to mention this while we pass this project on. If someone else wants to continue working or to Dr. Mehlhase if she is assigning to some one. 

Good thought, we dont have a ot of time figuring this out

**Comment by trevorforrey** [comment]
@vmadaraj Can you add this as an _issue_ on the repo? That should be sufficient.

**Comment by vmadaraj** [comment]
Sure @trevorforrey I shall add that once you merge everything

**Pull request merged**
