### PR TITLE
Sanay

### PR DESCRIPTION
**Pull request by sanaydevi**
Please view the average comments function. At first I hit the issue comments api and then for each issue number I hit the pull/comments api. 
To run it: 
tsc avgComments.ts
node avgComments.js
uncomment last line "//getNumCommets("ser574-green-team", "taigit");" to run the function. 
Let me know if you think this is correct. Thanks.

### CODE REVIEW

**Comment by PaHorton** [comment]
I have not run it yet because there are some pretty big issues with the structure of this. 
1. The code needs to be integrated into the library. Right now the code is sitting in it's own folder and is not accessible to the front end team. Please look at how others have done this in `taigit/src/libraries/GitHub/`. 
2. This request is merging into master, and needs to be merged into dev.
3. The request adds many `.idea` files and `node_module` folders which should never be committed. 
4. The request commits the compiled `.js` file. If the code is properly integrated into the library then there is no need to compile any typescript code as the front end will do it for us.

**Comment by sanaydevi** [comment]
Yes Paul i know it is not integrated into the main folder, I just wanted you to run it and check the logic, the only thing i will commit then to the dev folder is the typescript file.

**Comment by dlahtine** [comment]
You are adding project files in this commit as well; make sure those are not present.

**Comment by PaHorton** [comment]
This PR is a duplicate of #40

**Pull request closed without merging**
