### PR TITLE
Initial clean up commit

### PR DESCRIPTION
**Pull request by HalcyonAura**
Removing deprecated folders and cleaning up taiga.ts. This should be merged after everyone else's PRs are done

### CODE REVIEW

**Comment by trevorforrey** [comment]
Is this something that you're still looking to get merged in? Not sure if anything has changed regarding this PR.

**Comment by PaHorton** [comment]
I agree with trevor. I can close this out.

**Comment by PaHorton** [comment]
Wait there's a cleanup commit on it!

**Comment by HalcyonAura** [comment]
@PaHorton @trevorforrey in my efforts to rebase I think I may have introduced issues. Mind looking over everything to see if anything's missing/wrong/etc?

**Comment by trevorforrey** [comment]
```
Module parse failed: Identifier 'sprint_list' has already been declared (460:16)
You may need an appropriate loader to handle this file type.
| }
| 
> export function sprint_list(_x11) {
|   return _sprint_list2.apply(this, arguments);
| }
```

**Comment by HalcyonAura** [comment]
> Looks like when you rebased it introduced multiple sprint_list functions?
Yeah I caught that after I sent it to you guys reviewing taiga stuff. It seems the rebase didn't keep my conflict edit or (most likely) I goofed up and didn't save properly.

**Comment by trevorforrey** [comment]
No worries. Is it ready for review now?

**Pull request merged**
