### PR TITLE
US139 Task155 API to return task used time

### PR DESCRIPTION
**Pull request by xiangweizheng**
This call return a task used time based on task Id.
There are  timecost will be returned.
 *               timecost: number,  //time of history entry cost in milliseconds
 *               acctime: number,   //time of task accumulated of this history entry cost in milliseconds

To Test add following code in Taiga.js:
import {task_assessment_time}  from '../libraries/Taiga'

{console.log(task_assessment_time(2577741).then((val) => {console.log('fe', val)} ))}

Expected Result:
fe (3) [{…}, {…}, {…}] 0: {date: 1541629794485, timecost_m: 0, acctime_m: 0, timecost_h: 0, acctime_h: 0, …} 1: acctime_h: 211.73466694444443 acctime_m: 762244801 date: 1542392039286 status_trans: (2) ["In progress", "Ready for test"] timecost_h: 211.73466694444443 timecost_m: 762244801 __proto__: Object 2: {date: 1543257817335, timecost_m: 1628022850, acctime_m: 1628022850, timecost_h: 452.2285694444445, acctime_h: 452.2285694444445, …} length: 3 __proto__: Array(0)

### CODE REVIEW

**Comment by HalcyonAura** [comment]
I'm a little puzzled as to the amount of times here. Why do we need milleseconds and hours etc?
Could we not build a timestamp structure that shows the time per transition period, and time total, etc?
For example:
`total_time_accumulated (or something equivalent or shorter) = "02:34:35";`
where the above says the task took 2 hours, 34 minutes, 35 seconds which began from the moment a new task moved to in progress until it reached closed.
`time_in_progress = "00:30:21"`
`time_in_testing = ...`
I'm not sure if the information you are retrieving allows for this. But I think it would give frontend better data to work with.

**Comment by xiangweizheng** [comment]
As user story and burndown chart are calculated with hours. I can simply remove the time return with milisecond.  And original thought to keep milisecond time is to keep accuracy.

**Comment by xiangweizheng** [comment]
> I'm a little puzzled as to the amount of times here. Why do we need milleseconds and hours etc?
> Could we not build a timestamp structure that shows the time per transition period, and time total, etc?
> For example:
> `total_time_accumulated (or something equivalent or shorter) = "02:34:35";`
> where the above says the task took 2 hours, 34 minutes, 35 seconds which began from the moment a new task moved to in progress until it reached closed.
> `time_in_progress = "00:30:21"`
> `time_in_testing = ...`
> I'm not sure if the information you are retrieving allows for this. But I think it would give frontend better data to work with.

**Comment by xiangweizheng** [comment]
> I'm a little puzzled as to the amount of times here. Why do we need milleseconds and hours etc?
> Could we not build a timestamp structure that shows the time per transition period, and time total, etc?
> For example:
> `total_time_accumulated (or something equivalent or shorter) = "02:34:35";`
> where the above says the task took 2 hours, 34 minutes, 35 seconds which began from the moment a new task moved to in progress until it reached closed.
> `time_in_progress = "00:30:21"`
> `time_in_testing = ...`
> I'm not sure if the information you are retrieving allows for this. But I think it would give frontend better data to work with.

As user story and burndown chart are calculated with hours. I can simply remove the time return with milisecond. And the original thought to keep milisecond time is to keep accuracy.

**Comment by xiangweizheng** [comment]
John and Cecillia, your comments are conflicting. I am not sure whom to follow. As Cecillia is the scrum master, I will keep current version as Cecillia's suggestion. I can make a change after you reach an agreement. Thank you for the review.

**Comment by HalcyonAura** [comment]
> John and Cecillia, your comments are conflicting. I am not sure whom to follow. As Cecillia is the scrum master, I will keep current version as Cecillia's suggestion. I can make a change after you reach an agreement. Thank you for the review.

John has made a valid point with front end handling the conversion themselves, it would be better to follow his comment

**Comment by xiangweizheng** [comment]
> > John and Cecillia, your comments are conflicting. I am not sure whom to follow. As Cecillia is the scrum master, I will keep current version as Cecillia's suggestion. I can make a change after you reach an agreement. Thank you for the review.
> 
> John has made a valid point with front end handling the conversion themselves, it would be better to follow his comment

OK. I change it back.

**Pull request merged**
