### PR TITLE
Us#203 task#212 api connect

### PR DESCRIPTION
**Pull request by jjsoni96**
I was able to connect the component with the API but unless it is merged with the dev, I am not sure actual data will come up or not.

### CODE REVIEW

**Comment by trevorforrey** [comment]
Rebase your branch onto origin dev and then you can test with the changes on most recent dev

**Comment by jjsoni96** [comment]
Merge conflicts have been resolved and I am able to get the output. The date format is too long and Paul is going to fix that. Otherwise, everything is running fine.

**Comment by jjsoni96** [comment]
GitHubContribution Output

**Comment by jjsoni96** [comment]
Fixed Date Format

**Pull request merged**
