### PR TITLE
Redux structure

### PR DESCRIPTION
**Pull request by trevorforrey**
This creates the basic redux store structure for the project.

This branch connects team member info, and some small GitHub and Taiga data to the redux store.

- _src/actions_ contains all actions on the store that the UI will call (GitHub has one that utilizes a GitHub api call)
- _src/reducers_ contains code that gets run when an action is called, and grabs data from the result of the action to update the store

_Note: you'll need to run `npm install` before testing as I've added two new dependencies_

### CODE REVIEW

**Comment by xiangweizheng** [comment]
Dev works good for me. I would say it is good to merge to master if there is no other issues found.

**Comment by trevorforrey** [comment]
Example of redux store connection (calls github api to get a list of branches)

screen shot 2019-03-05 at 6 47 36 pm

**Comment by trevorforrey** [comment]
Refactored GitHub page to `use selectors to get computed data back from the store`. An example can be seen in `reducers/githubReducer` which has a function that returns back the chartData object needed by chartjs to display the graph on the bottom left. 

screen shot 2019-03-08 at 10 05 35 am

**Comment by trevorforrey** [comment]
Bringing into dev with @vmadaraj's approval!

**Pull request merged**
